name: Auto-update Scoop bucket

on:
  schedule:
    # 语法：分 时 日 月 周
    # */4 表示“每隔 4 个小时”执行一次（即 0点, 4点, 8点, 12点, 16点, 20点）
    - cron: '0 */4 * * *'
  workflow_dispatch: # 允许手动点击运行

jobs:
  update-manifests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update configurations
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
